### ISSUE TITLE
TypeError: encoding without a string argument

### ISSUE THREAD

**Issue by anzhaozhong** [iexbase/tron-api-python#36]
https://github.com/iexbase/tron-api-python/blob/ee9b69ff84696b9c7f417989fad2a77a395fe113/tronapi/main.py#L191

**Comment by anzhaozhong** [comment]
When Tron class init, the default_address param should be Base58 format, otherwise the private_key would be None. because _private_base58 != _base58.

**Comment by anzhaozhong** [comment]
Traceback (most recent call last):
  File "/home/an/Desktop/python/walletserver/exjrpc/tron_rpc.py", line 82, in <module>
    print(client.withdrawal(TRON_WALLET_ADDRESS_HEX, 0.9))
  File "/home/an/Desktop/python/walletserver/exjrpc/tron_rpc.py", line 69, in withdrawal
    tx = self.trx.send_trx(to_address, amount)
  File "/home/an/virtualenvs/env/lib/python3.6/site-packages/tronapi/trx.py", line 375, in send_trx
    return self.send_transaction(to, amount, options)
  File "/home/an/virtualenvs/env/lib/python3.6/site-packages/tronapi/trx.py", line 404, in send_transaction
    sign = self.sign(tx)
  File "/home/an/virtualenvs/env/lib/python3.6/site-packages/tronapi/trx.py", line 549, in sign
    address = self.tron.address.from_private_key(self.tron.private_key).hex.lower()
  File "/home/an/virtualenvs/env/lib/python3.6/site-packages/tronapi/common/account.py", line 59, in from_private_key
    return PrivateKey(private_key).address
  File "/home/an/virtualenvs/env/lib/python3.6/site-packages/tronapi/common/account.py", line 70, in __init__
    _private = unhexlify(bytes(private_key, encoding='utf8'))
TypeError: encoding without a string argument

**Comment by serderovsh** [comment]
#22
